const {test}=require('node:test'),assert=require('node:assert/strict'),{SetupStep}=require('../js/inuyasha/setup-engine.js');
function fixture(){const players=Object.fromEntries(['A','B'].map(p=>[p,{library:Array.from({length:30},(_,i)=>({instanceId:p+i,name:'Deck '+i,owner:p,zone:'library'})),hand:[],play:[],discard:[]}]));const s=new SetupStep({players,activePlayerId:'A'});s.start(true);return s;}
function card(s,id,type='Character',p='A',extra={}){const c={instanceId:id,name:id,cardType:type,printedDeckCost:1,unique:false,owner:p,originalOwner:p,zone:'hand',faceUp:true,ready:true,...extra};s.players[p].hand.push(c);return c;}
test('start/end active then opponent, full blocks, stops at Battle Start',()=>{const s=fixture();assert.deepEqual(s.events.map(e=>[e.window,e.subjectPlayerId]),[['start_of_setup','A'],['start_of_setup','B']]);assert.throws(()=>s.finish('B'));s.finish('A');assert.equal(s.actor,'B');s.finish('B');assert.equal(s.phase,'BATTLE_START');assert.deepEqual(s.events.slice(-2).map(e=>e.subjectPlayerId),['A','B']);assert.throws(()=>s.finish('B'));});
test('characters locations items any order and full costs',()=>{const s=fixture();card(s,'L','Location');card(s,'C');card(s,'I','Item');card(s,'L2','Location');s.play('A','L');s.play('A','C');s.play('A','I',{hostId:'C'});s.play('A','L2');assert.equal(s.players.A.discard.length,4);assert.equal(s.counts.A,1);assert.equal(s.find('I').attachedTo,'C');});
test('two characters per player including overlay; third rejection is atomic',()=>{const s=fixture();card(s,'c','Character','A',{name:'Kagome, Student',unique:true});card(s,'d','Character','A',{name:'Kagome, Archer',unique:true});card(s,'third');s.play('A','c');s.play('A','d');const before=s.players.A.library.length;assert.throws(()=>s.play('A','third'),/two Characters/);assert.equal(s.players.A.library.length,before);assert.equal(s.find('c').zone,'discard');s.finish('A');for(const id of ['b','b2']){card(s,id,'Character','B');s.play('B',id);}assert.equal(s.counts.B,2);});
test('same surname, duplicate location and occupied item slot blocked',()=>{const s=fixture();for(const id of ['c','copy'])card(s,id,'Character','A',{name:'Shippo, Artist',unique:true});s.play('A','c');assert.throws(()=>s.play('A','copy'));for(const id of ['l','l2'])card(s,id,'Location','A',{name:'Village'});s.play('A','l');assert.throws(()=>s.play('A','l2'));for(const id of ['i','i2'])card(s,id,'Item');s.play('A','i',{hostId:'c'});assert.throws(()=>s.play('A','i2',{hostId:'c'}));});
test('unknown printed cost/Unique, wrong actor and insufficient deck fail before mutation',()=>{const s=fixture();card(s,'c','Character','A',{printedDeckCost:null,unique:undefined});assert.throws(()=>s.play('A','c'));assert.throws(()=>s.play('B','c'));assert.equal(s.players.A.discard.length,0);assert.throws(()=>s.play('A','c',{deckCost:99,unique:true}));s.play('A','c',{deckCost:2,unique:true});assert.equal(s.players.A.discard.length,2);});
test('when played callback/window order follows ARD',()=>{const s=fixture(),seen=[];s.onWindow=e=>seen.push('window:'+e.cardId);card(s,'c','Character','A',{whenPlayed:()=>seen.push('effect:c')});card(s,'i','Item','A',{whenPlayed:()=>seen.push('effect:i')});s.play('A','c');s.play('A','i',{hostId:'c'});assert.deepEqual(seen,['effect:c','window:c','window:i','effect:i']);});
test('Tiara requires Chokyukai, steals enemy, counts limit, removal restores owner',()=>{const s=fixture();card(s,'cho','Character','A',{name:'Chokyukai, Descendant'});s.play('A','cho');const victim=card(s,'victim','Character','B');s.move(victim,'play');card(s,'tiara','Item','A',{name:"Chokyukai's Tiara"});s.play('A','tiara',{hostId:'victim'});assert.equal(victim.owner,'A');assert.equal(s.counts.A,2);s.removeAttachment('tiara');assert.equal(victim.owner,'B');});
test('Scent returns controlled character, searches one zone, reveals and offers cut once',()=>{const s=fixture();card(s,'c');s.play('A','c');card(s,'s','Event','A',{name:'Following the Scent'});const loc=card(s,'loc','Location');s.move(loc,'library');s.play('A','s',{returnId:'c',searchZone:'library',searchIds:['loc'],shuffle:x=>x});assert.equal(s.find('c').zone,'hand');assert.equal(loc.zone,'hand');assert.deepEqual(s.revealed,[['loc']]);assert.deepEqual(s.cutOffers,[{from:'A',to:'B'}]);s.play('A','c');card(s,'s2','Event','A',{name:'Following the Scent'});assert.throws(()=>s.play('A','s2',{returnId:'c',searchZone:'discard'}),/once/);});
test('Scent invalid locations and unknown Event cannot spend deck cost',()=>{const s=fixture();card(s,'c');s.play('A','c');card(s,'s','Event','A',{name:'Following the Scent'});const before=s.players.A.library.length;assert.throws(()=>s.play('A','s',{returnId:'c',searchZone:'library',searchIds:['c']}));assert.equal(s.players.A.library.length,before);card(s,'event','Event');assert.throws(()=>s.play('A','event'));});
test('Shroom permits same-version Shippo and remains active defeated; cannot discard by effect',()=>{const s=fixture();card(s,'ship','Character','A',{name:'Shippo, Artist',unique:true});s.play('A','ship');card(s,'shroom','Event','A',{name:"Shippo's Shroom"});s.play('A','shroom',{hostId:'ship'});card(s,'ship2','Character','A',{name:'Shippo, Artist',unique:true});s.play('A','ship2');assert.equal(s.find('ship').zone,'play');s.find('ship').defeated=true;s.find('ship').faceUp=false;assert.equal(s.unique(s.find('ship2'),'A'),false);assert.throws(()=>s.removeAttachment('shroom'));});
test('Item Technique moves legal item without replay window; illegal new host blocked',()=>{const s=fixture();for(const id of ['c','d']){card(s,id);s.play('A',id);}card(s,'i','Item');s.play('A','i',{hostId:'c'});card(s,'t','Event','A',{name:"Shippo's Item Technique"});const events=s.events.length;s.play('A','t',{hostId:'d',itemId:'i'});assert.equal(s.find('i').attachedTo,'d');assert.equal(s.events.length,events);});
test('cannot enter Set Up before Draw or repeat its start',()=>{const s=fixture();assert.throws(()=>s.start(true));const s2=new SetupStep({players:s.players,activePlayerId:'A'});assert.throws(()=>s2.start(false));});
