(function(root,factory){
  const api=factory();
  if(typeof module!=='undefined'&&module.exports) module.exports=api;
  else root.CoreMagic=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(){
  'use strict';
  const VERSION='CORE_MATCH_0.1';
  const PHASES={MAIN1:'MAIN1',ATTACK:'ATTACK',POST_ATTACK:'POST_ATTACK',BLOCK:'BLOCK',POST_BLOCK:'POST_BLOCK',MAIN2:'MAIN2',END:'END'};
  const CARDS={
    'Mountain':{name:'Mountain',type:'Land',cost:'',text:'{T}: Add {R}.',produces:'R'},
    "Mons's Goblin Raiders":{name:"Mons's Goblin Raiders",type:'Creature',cost:'R',power:1,toughness:1,text:'A simple 1/1 creature.'},
    'Goblin Piker':{name:'Goblin Piker',type:'Creature',cost:'1R',power:2,toughness:1,text:'A simple 2/1 creature.'},
    'Gray Ogre':{name:'Gray Ogre',type:'Creature',cost:'2R',power:2,toughness:2,text:'A simple 2/2 creature.'},
    'Hurloon Minotaur':{name:'Hurloon Minotaur',type:'Creature',cost:'1RR',power:2,toughness:3,text:'A simple 2/3 creature.'},
    'Hill Giant':{name:'Hill Giant',type:'Creature',cost:'3R',power:3,toughness:3,text:'A simple 3/3 creature.'},
    'Shock':{name:'Shock',type:'Instant',cost:'R',text:'Shock deals 2 damage to any target.',effect:{kind:'damage',amount:2,target:'any'}},
    'Lightning Strike':{name:'Lightning Strike',type:'Instant',cost:'1R',text:'Lightning Strike deals 3 damage to any target.',effect:{kind:'damage',amount:3,target:'any'}},
    'Volcanic Hammer':{name:'Volcanic Hammer',type:'Sorcery',cost:'1R',text:'Volcanic Hammer deals 3 damage to any target.',effect:{kind:'damage',amount:3,target:'any'}},
    'Lava Axe':{name:'Lava Axe',type:'Sorcery',cost:'4R',text:'Lava Axe deals 5 damage to target player.',effect:{kind:'damage',amount:5,target:'player'}}
  };
  const DECK_COUNTS={Mountain:24,"Mons's Goblin Raiders":4,'Goblin Piker':4,'Gray Ogre':4,'Hurloon Minotaur':4,'Hill Giant':4,'Shock':4,'Lightning Strike':4,'Volcanic Hammer':4,'Lava Axe':4};
  function clone(v){return JSON.parse(JSON.stringify(v));}
  function hashSeed(s){let h=2166136261>>>0;for(const ch of String(s)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)>>>0;}return h||1;}
  function next(game){let x=game.rng>>>0;x^=x<<13;x^=x>>>17;x^=x<<5;game.rng=x>>>0;return (game.rng>>>0)/4294967296;}
  function shuffle(game,a){for(let i=a.length-1;i>0;i--){const j=Math.floor(next(game)*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
  function other(p){return p==='User'?'Assistant':'User';}
  function cardDef(card){return CARDS[card.name];}
  function makeCard(name,owner,n){return {id:`${owner[0]}-${n}-${name.replace(/[^A-Za-z0-9]/g,'').slice(0,8)}`,name,owner,tapped:false,damage:0,enteredTurn:0};}
  function buildDeck(owner){const deck=[];let n=1;for(const [name,count] of Object.entries(DECK_COUNTS))for(let i=0;i<count;i++)deck.push(makeCard(name,owner,n++));return deck;}
  function log(g,msg){g.log.push(msg);if(g.log.length>400)g.log.splice(0,g.log.length-400);}
  function draw(g,p,n=1){const pl=g.players[p];for(let i=0;i<n;i++){if(!pl.library.length){g.over=true;g.winner=other(p);log(g,`${p} attempted to draw from an empty library and loses.`);return;}pl.hand.push(pl.library.shift());log(g,`${p} draws a card.`);}}
  function costTotal(cost){if(!cost)return 0;const m=String(cost).match(/\d+/);const generic=m?Number(m[0]):0;const colored=(String(cost).match(/[WUBRG]/g)||[]).length;return generic+colored;}
  function untappedMountains(g,p){return g.players[p].battlefield.filter(c=>c.name==='Mountain'&&!c.tapped);}
  function canPay(g,p,cost){return untappedMountains(g,p).length>=costTotal(cost);}
  function pay(g,p,cost){const need=costTotal(cost),lands=untappedMountains(g,p);if(lands.length<need)throw new Error('Not enough untapped Mountains.');for(let i=0;i<need;i++)lands[i].tapped=true;}
  function isMain(g){return g.phase===PHASES.MAIN1||g.phase===PHASES.MAIN2;}
  function legalTargets(g,card){const d=cardDef(card);if(!d.effect)return [];const out=[];if(d.effect.target==='any'||d.effect.target==='player'){out.push({key:'P:User',label:`You (${g.players.User.life} life)`},{key:'P:Assistant',label:`Opponent (${g.players.Assistant.life} life)`});}
    if(d.effect.target==='any')for(const p of ['User','Assistant'])for(const c of g.players[p].battlefield){const cd=cardDef(c);if(cd.type==='Creature')out.push({key:`C:${c.id}`,label:`${p}: ${c.name} ${cd.power}/${cd.toughness} (${c.damage} dmg)`});}
    return out;
  }
  function findPermanent(g,id){for(const p of ['User','Assistant']){const i=g.players[p].battlefield.findIndex(c=>c.id===id);if(i>=0)return {player:p,index:i,card:g.players[p].battlefield[i]};}return null;}
  function canCast(g,p,card){if(g.over||g.priority!==p)return false;const d=cardDef(card);if(!d||d.type==='Land')return false;if(!canPay(g,p,d.cost))return false;if(d.type==='Instant')return true;return g.active===p&&isMain(g)&&g.stack.length===0;}
  function playLand(g,p,cardId){if(g.over)throw new Error('Game is over.');if(g.active!==p||g.priority!==p||!isMain(g)||g.stack.length)throw new Error('A land can only be played during your main phase with an empty stack.');const pl=g.players[p];if(pl.landPlayed)throw new Error('You already played a land this turn.');const i=pl.hand.findIndex(c=>c.id===cardId);if(i<0||pl.hand[i].name!=='Mountain')throw new Error('That card is not a playable Mountain.');const [card]=pl.hand.splice(i,1);card.enteredTurn=g.turn;pl.battlefield.push(card);pl.landPlayed=true;g.passes=0;log(g,`${p} plays Mountain.`);return card;}
  function cast(g,p,cardId,targetKey){if(g.over)throw new Error('Game is over.');const pl=g.players[p],i=pl.hand.findIndex(c=>c.id===cardId);if(i<0)throw new Error('Card is not in hand.');const card=pl.hand[i],d=cardDef(card);if(!canCast(g,p,card))throw new Error('That spell cannot be cast now.');let target=null;if(d.effect){const legal=legalTargets(g,card).map(x=>x.key);if(!legal.includes(targetKey))throw new Error('Choose a legal target.');target=targetKey;}
    pay(g,p,d.cost);pl.hand.splice(i,1);g.stack.push({card,controller:p,target});g.passes=0;log(g,`${p} casts ${card.name}${target?` targeting ${target}`:''}.`);return card;
  }
  function sba(g){let changed=true;while(changed&&!g.over){changed=false;for(const p of ['User','Assistant']){const pl=g.players[p];for(let i=pl.battlefield.length-1;i>=0;i--){const c=pl.battlefield[i],d=cardDef(c);if(d.type==='Creature'&&(d.toughness<=0||c.damage>=d.toughness)){pl.battlefield.splice(i,1);c.damage=0;c.tapped=false;pl.graveyard.push(c);log(g,`${c.name} is put into ${p}'s graveyard for lethal damage.`);changed=true;}}if(pl.life<=0&&!g.over){g.over=true;g.winner=other(p);log(g,`${p} has ${pl.life} life and loses. ${g.winner} wins.`);}}}}
  function applyDamage(g,targetKey,amount,source){if(targetKey.startsWith('P:')){const p=targetKey.slice(2);g.players[p].life-=amount;log(g,`${source} deals ${amount} damage to ${p} (${g.players[p].life} life).`);return true;}if(targetKey.startsWith('C:')){const f=findPermanent(g,targetKey.slice(2));if(!f){log(g,`${source} has no legal target on resolution and does nothing.`);return false;}f.card.damage+=amount;log(g,`${source} deals ${amount} damage to ${f.card.name}.`);return true;}return false;}
  function resolveTop(g){if(!g.stack.length)return null;const item=g.stack.pop(),card=item.card,d=cardDef(card),pl=g.players[item.controller];if(d.type==='Creature'){card.enteredTurn=g.turn;card.tapped=false;card.damage=0;pl.battlefield.push(card);log(g,`${card.name} resolves onto ${item.controller}'s battlefield.`);}else{let resolved=true;if(d.effect?.kind==='damage')resolved=applyDamage(g,item.target,d.effect.amount,card.name);pl.graveyard.push(card);if(resolved)log(g,`${card.name} finishes resolving.`);}sba(g);return card;}
  function startTurn(g,p,drawCard=true){g.active=p;g.turn+=1;g.phase=PHASES.MAIN1;g.priority=p;g.passes=0;g.combat={attackers:[],blocks:{}};for(const c of g.players[p].battlefield){c.tapped=false;c.damage=0;}for(const c of g.players[other(p)].battlefield)c.damage=0;g.players[p].landPlayed=false;log(g,`Turn ${g.turn}: ${p}'s turn begins.`);if(drawCard)draw(g,p,1);sba(g);}
  function newGame(seed='FOCUSED-MAGIC-CORE',difficulty='Regular'){
    const g={version:VERSION,seed:String(seed),rng:hashSeed(seed),difficulty,turn:1,active:'User',phase:PHASES.MAIN1,priority:'User',passes:0,stack:[],combat:{attackers:[],blocks:{}},over:false,winner:null,log:[],players:{User:{life:20,library:[],hand:[],battlefield:[],graveyard:[],landPlayed:false},Assistant:{life:20,library:[],hand:[],battlefield:[],graveyard:[],landPlayed:false}}};
    g.players.User.library=shuffle(g,buildDeck('User'));g.players.Assistant.library=shuffle(g,buildDeck('Assistant'));draw(g,'User',7);draw(g,'Assistant',7);log(g,'Core Match begins. User plays first and skips the first-turn draw.');return g;
  }
  function eligibleAttackers(g,p){return g.players[p].battlefield.filter(c=>{const d=cardDef(c);return d.type==='Creature'&&!c.tapped&&c.enteredTurn<g.turn;});}
  function declareAttackers(g,p,ids){if(g.over||g.phase!==PHASES.ATTACK||g.active!==p)throw new Error('It is not your declare attackers step.');const eligible=new Set(eligibleAttackers(g,p).map(c=>c.id));const uniq=[...new Set(ids||[])];if(uniq.some(id=>!eligible.has(id)))throw new Error('One or more attackers are not eligible.');for(const id of uniq){const c=g.players[p].battlefield.find(x=>x.id===id);c.tapped=true;}g.combat={attackers:uniq,blocks:{}};log(g,`${p} declares ${uniq.length} attacker${uniq.length===1?'':'s'}.`);if(!uniq.length){g.phase=PHASES.MAIN2;g.priority=p;g.passes=0;log(g,'No attackers. Combat is skipped.');}else{g.phase=PHASES.POST_ATTACK;g.priority=p;g.passes=0;}return uniq;}
  function declareBlocks(g,defender,assignments){if(g.over||g.phase!==PHASES.BLOCK||other(g.active)!==defender)throw new Error('It is not your declare blockers step.');const attackers=new Set(g.combat.attackers),used=new Set(),blocks={};for(const [attacker,blocker] of Object.entries(assignments||{})){if(!attackers.has(attacker)||!blocker)continue;if(used.has(blocker))throw new Error('A blocker can only block one attacker in Core Match Alpha.');const f=findPermanent(g,blocker);if(!f||f.player!==defender||cardDef(f.card).type!=='Creature')throw new Error('Illegal blocker.');used.add(blocker);blocks[attacker]=blocker;}g.combat.blocks=blocks;g.phase=PHASES.POST_BLOCK;g.priority=g.active;g.passes=0;log(g,`${defender} declares ${Object.keys(blocks).length} blocker${Object.keys(blocks).length===1?'':'s'}.`);return blocks;}
  function combatDamage(g){const attackerPlayer=g.active,defender=other(attackerPlayer);for(const aid of g.combat.attackers){const af=findPermanent(g,aid);if(!af)continue;const ad=cardDef(af.card),bid=g.combat.blocks[aid];if(bid){const bf=findPermanent(g,bid);if(bf){const bd=cardDef(bf.card);af.card.damage+=bd.power;bf.card.damage+=ad.power;log(g,`${af.card.name} and ${bf.card.name} deal combat damage to each other.`);}}else{g.players[defender].life-=ad.power;log(g,`${af.card.name} deals ${ad.power} combat damage to ${defender} (${g.players[defender].life} life).`);}}sba(g);g.combat={attackers:[],blocks:{}};if(!g.over){g.phase=PHASES.MAIN2;g.priority=g.active;g.passes=0;log(g,'Combat damage ends. Postcombat main phase begins.');}}
  function advanceEmpty(g){if(g.phase===PHASES.MAIN1){g.phase=PHASES.ATTACK;g.priority=g.active;log(g,'Declare attackers step.');return;}
    if(g.phase===PHASES.POST_ATTACK){g.phase=PHASES.BLOCK;g.priority=other(g.active);log(g,'Declare blockers step.');return;}
    if(g.phase===PHASES.POST_BLOCK){combatDamage(g);return;}
    if(g.phase===PHASES.MAIN2){g.phase=PHASES.END;g.priority=g.active;log(g,'End step.');return;}
    if(g.phase===PHASES.END){startTurn(g,other(g.active),true);return;}
    throw new Error(`Cannot pass through phase ${g.phase}.`);
  }
  function passPriority(g,p){if(g.over)throw new Error('Game is over.');if(g.phase===PHASES.ATTACK||g.phase===PHASES.BLOCK)throw new Error('Complete the combat declaration first.');if(g.priority!==p)throw new Error('You do not have priority.');g.passes+=1;log(g,`${p} passes priority.`);if(g.passes<2){g.priority=other(p);return {type:'priority'};}g.passes=0;if(g.stack.length){resolveTop(g);if(!g.over){g.priority=g.active;log(g,`${g.active} receives priority after resolution.`);}return {type:'resolved'};}advanceEmpty(g);return {type:'phase'};}
  function concede(g,p){if(g.over)return;g.over=true;g.winner=other(p);log(g,`${p} concedes. ${g.winner} wins.`);}
  function cardValue(c){const d=cardDef(c);if(d.type==='Creature')return d.power+d.toughness+costTotal(d.cost)*0.2;if(d.effect)return d.effect.amount+costTotal(d.cost)*0.1;return 0;}
  function aiTarget(g,card,difficulty){const d=cardDef(card),enemy='User';if(!d.effect)return null;if(d.effect.target==='player')return 'P:User';const amount=d.effect.amount;const creatures=g.players.User.battlefield.filter(c=>cardDef(c).type==='Creature');const killable=creatures.filter(c=>cardDef(c).toughness-c.damage<=amount).sort((a,b)=>cardValue(b)-cardValue(a));if(difficulty==='Apprentice'){const opts=legalTargets(g,card).filter(x=>!x.key.startsWith('P:Assistant')&&!x.label.startsWith('Assistant:'));return opts.length?opts[Math.floor(next(g)*opts.length)].key:'P:User';}
    if(g.players.User.life<=amount)return 'P:User';if(killable.length)return `C:${killable[0].id}`;return 'P:User';}
  function aiChooseCast(g){const p='Assistant',hand=g.players[p].hand.filter(c=>canCast(g,p,c));if(!hand.length)return null;const diff=g.difficulty||'Regular';if(diff==='Apprentice')return hand[Math.floor(next(g)*hand.length)];const lethal=hand.find(c=>cardDef(c).effect?.kind==='damage'&&cardDef(c).effect.amount>=g.players.User.life);if(lethal)return lethal;const killSpell=hand.filter(c=>cardDef(c).effect?.kind==='damage'&&legalTargets(g,c).some(t=>t.key.startsWith('C:')&&t.label.startsWith('User:'))).sort((a,b)=>cardDef(a).cost.length-cardDef(b).cost.length)[0];if(killSpell&&diff==='Expert')return killSpell;const creatures=hand.filter(c=>cardDef(c).type==='Creature').sort((a,b)=>costTotal(cardDef(b).cost)-costTotal(cardDef(a).cost));if(creatures.length)return creatures[0];const burns=hand.filter(c=>cardDef(c).effect?.kind==='damage').sort((a,b)=>cardDef(b).effect.amount-cardDef(a).effect.amount);return burns[0]||hand[0];}
  function aiAttackers(g){const eligible=eligibleAttackers(g,'Assistant');if(g.difficulty==='Apprentice')return eligible.filter(()=>next(g)>.45).map(c=>c.id);if(g.difficulty==='Regular')return eligible.map(c=>c.id);const blockers=g.players.User.battlefield.filter(c=>cardDef(c).type==='Creature');return eligible.filter(a=>{const ad=cardDef(a);return !blockers.some(b=>{const bd=cardDef(b);return bd.power>=ad.toughness&&bd.toughness>ad.power;});}).map(c=>c.id);}
  function aiBlocks(g){const attackers=g.combat.attackers.map(id=>findPermanent(g,id)).filter(Boolean).map(x=>x.card);const blockers=g.players.Assistant.battlefield.filter(c=>cardDef(c).type==='Creature');const used=new Set(),out={};const ordered=[...attackers].sort((a,b)=>cardDef(b).power-cardDef(a).power);for(const a of ordered){const ad=cardDef(a);let choices=blockers.filter(b=>!used.has(b.id));if(!choices.length)break;let pick=null;if(g.difficulty==='Apprentice'){if(next(g)>.5)pick=choices[Math.floor(next(g)*choices.length)];}else{choices.sort((x,y)=>{const xd=cardDef(x),yd=cardDef(y);const xs=(xd.toughness>ad.power?3:0)+(xd.power>=ad.toughness?4:0)-cardValue(x)*.05;const ys=(yd.toughness>ad.power?3:0)+(yd.power>=ad.toughness?4:0)-cardValue(y)*.05;return ys-xs;});const best=choices[0],bd=cardDef(best);if(bd.power>=ad.toughness||bd.toughness>ad.power||g.players.Assistant.life<=ad.power+2)pick=best;}if(pick){out[a.id]=pick.id;used.add(pick.id);}}
    return out;
  }
  function aiStep(g){if(g.over)return {type:'over'};if(g.phase===PHASES.ATTACK&&g.active==='Assistant'){declareAttackers(g,'Assistant',aiAttackers(g));return {type:'attack'};}if(g.phase===PHASES.BLOCK&&other(g.active)==='Assistant'){declareBlocks(g,'Assistant',aiBlocks(g));return {type:'block'};}if(g.priority!=='Assistant')return {type:'wait'};
    const pl=g.players.Assistant;if(g.active==='Assistant'&&isMain(g)&&g.stack.length===0&&!pl.landPlayed){const land=pl.hand.find(c=>c.name==='Mountain');if(land){playLand(g,'Assistant',land.id);return {type:'land'};}}
    const castable=aiChooseCast(g);if(castable){const target=cardDef(castable).effect?aiTarget(g,castable,g.difficulty):null;cast(g,'Assistant',castable.id,target);return {type:'cast',card:castable.name};}
    return passPriority(g,'Assistant');
  }
  function publicView(g){return clone(g);}
  function getCard(name){return clone(CARDS[name]);}
  return {VERSION,PHASES,CARDS,DECK_COUNTS,newGame,clone,cardDef,getCard,legalTargets,canCast,playLand,cast,passPriority,declareAttackers,declareBlocks,combatDamage,resolveTop,sba,concede,aiStep,eligibleAttackers,other,publicView,costTotal};
});

(function(){
'use strict';
const E=window.CoreMagic;let g=null,aiTimer=null;
const q=id=>document.getElementById(id);
function setStatus(t,bad=false){q('coreStatus').textContent=t;q('coreStatus').classList.toggle('bad-text',bad)}
function def(c){return E.CARDS[c.name]}
function phaseLabel(p){return ({MAIN1:'Precombat Main',ATTACK:'Declare Attackers',POST_ATTACK:'After Attackers — Priority',BLOCK:'Declare Blockers',POST_BLOCK:'After Blockers — Priority',MAIN2:'Postcombat Main',END:'End Step'})[p]||p}
function cardTile(c,owner,zone){const d=def(c),el=document.createElement('div');el.className='core-card'+(c.tapped?' tapped':'')+(g.combat.attackers.includes(c.id)?' attacking':'');let html=`<strong>${c.name}</strong><small>${d.type}${d.cost?' • '+d.cost:''}</small>`;if(d.type==='Creature')html+=`<span class="pt">${d.power}/${d.toughness}</span><small>${c.damage?c.damage+' damage marked • ':''}${c.enteredTurn>=g.turn?'summoning sick':''}</small>`;html+=`<small>${d.text}</small>`;el.innerHTML=html;
  if(owner==='User'&&zone==='hand'&&!g.over){if(d.type==='Land'){const b=document.createElement('button');b.textContent='Play land';b.disabled=!(g.active==='User'&&g.priority==='User'&&(g.phase==='MAIN1'||g.phase==='MAIN2')&&!g.stack.length&&!g.players.User.landPlayed);b.onclick=()=>act(()=>E.playLand(g,'User',c.id),'Land played.');el.appendChild(b)}else{let targetSel=null;if(d.effect){targetSel=document.createElement('select');for(const t of E.legalTargets(g,c)){const o=document.createElement('option');o.value=t.key;o.textContent=t.label;targetSel.appendChild(o)}el.appendChild(targetSel)}const b=document.createElement('button');b.textContent='Cast';b.disabled=!E.canCast(g,'User',c);b.onclick=()=>act(()=>E.cast(g,'User',c.id,targetSel?targetSel.value:null),`${c.name} cast.`);el.appendChild(b)}}
  if(owner==='User'&&zone==='battlefield'&&d.type==='Creature'&&g.phase==='ATTACK'&&g.active==='User'&&c.enteredTurn<g.turn&&!c.tapped){const lab=document.createElement('label');lab.style.display='block';lab.style.marginTop='5px';lab.innerHTML=`<input type="checkbox" data-core-attacker="${c.id}"> Attack`;el.appendChild(lab)}
  return el;
}
function fill(id,cards,owner,zone,hidden=false){const box=q(id);box.innerHTML='';if(hidden){for(let i=0;i<cards.length;i++){const e=document.createElement('div');e.className='core-card core-hidden';e.textContent='Hidden card';box.appendChild(e)}return;}for(const c of cards)box.appendChild(cardTile(c,owner,zone));}
function renderCombat(){const box=q('coreCombatControls');box.innerHTML='';box.classList.add('hidden');q('coreDeclareAttackers').classList.add('hidden');q('coreDeclareBlocks').classList.add('hidden');if(!g||g.over)return;
 if(g.phase==='ATTACK'&&g.active==='User'){box.classList.remove('hidden');box.innerHTML='<b>Choose attackers</b><div class="sub">Check eligible creatures on your battlefield, then declare them.</div>';q('coreDeclareAttackers').classList.remove('hidden')}
 if(g.phase==='BLOCK'&&E.other(g.active)==='User'){box.classList.remove('hidden');box.innerHTML='<b>Assign blockers</b><div class="sub">Core Match Alpha supports one blocker per attacker.</div>';const blockers=g.players.User.battlefield.filter(c=>def(c).type==='Creature');for(const aid of g.combat.attackers){let a=null;for(const p of ['User','Assistant'])a=g.players[p].battlefield.find(c=>c.id===aid)||a;if(!a)continue;const row=document.createElement('div');row.className='core-combat-row';const label=document.createElement('span');label.textContent=`Block ${a.name}`;const sel=document.createElement('select');sel.dataset.coreBlock=aid;sel.innerHTML='<option value="">No block</option>';for(const b of blockers){const o=document.createElement('option');o.value=b.id;o.textContent=`${b.name} ${def(b).power}/${def(b).toughness}`;sel.appendChild(o)}row.append(label,sel);box.appendChild(row)}q('coreDeclareBlocks').classList.remove('hidden')}
}
function render(){if(!g)return;q('coreTurn').textContent=g.turn;q('coreActive').textContent=g.active;q('corePhase').textContent=phaseLabel(g.phase);q('corePriority').textContent=(g.phase==='ATTACK'||g.phase==='BLOCK')?'—':g.priority;q('coreUserLife').textContent=g.players.User.life;q('coreAiLife').textContent=g.players.Assistant.life;q('coreUserLib').textContent=g.players.User.library.length;q('coreAiLib').textContent=g.players.Assistant.library.length;q('coreUserHandCount').textContent=g.players.User.hand.length;q('coreAiHandCount').textContent=g.players.Assistant.hand.length;q('coreUserGyCount').textContent=g.players.User.graveyard.length;q('coreAiGyCount').textContent=g.players.Assistant.graveyard.length;q('coreAiDifficultyLabel').textContent=g.difficulty;
 fill('coreUserBattlefield',g.players.User.battlefield,'User','battlefield');fill('coreUserHand',g.players.User.hand,'User','hand');fill('coreAiBattlefield',g.players.Assistant.battlefield,'Assistant','battlefield');fill('coreAiHand',g.players.Assistant.hand,'Assistant','hand',true);
 const stack=q('coreStack');stack.innerHTML='';if(!g.stack.length)stack.innerHTML='<div class="sub">Stack empty.</div>';for(const s of g.stack){const e=document.createElement('div');e.className='core-stack-item';e.textContent=`${s.controller}: ${s.card.name}${s.target?' → '+s.target:''}`;stack.appendChild(e)}
 q('coreLog').textContent=g.log.slice(-180).join('\n');q('coreLog').scrollTop=q('coreLog').scrollHeight;const pass=q('corePass');pass.disabled=g.over||g.priority!=='User'||g.phase==='ATTACK'||g.phase==='BLOCK';pass.classList.toggle('ready',!pass.disabled);renderCombat();q('coreGameOver').classList.toggle('hidden',!g.over);if(g.over)q('coreGameOver').textContent=`Game over — ${g.winner} wins.`;
}
function act(fn,msg){try{fn();setStatus(msg||'Action complete.');render();pumpAI()}catch(e){setStatus(e.message,true)}}
function pumpAI(){clearTimeout(aiTimer);if(!g||g.over){render();return}const needsAI=(g.phase==='ATTACK'&&g.active==='Assistant')||(g.phase==='BLOCK'&&E.other(g.active)==='Assistant')||g.priority==='Assistant';if(!needsAI){render();return}aiTimer=setTimeout(()=>{try{let guard=0;while(guard++<40&&!g.over){const need=(g.phase==='ATTACK'&&g.active==='Assistant')||(g.phase==='BLOCK'&&E.other(g.active)==='Assistant')||g.priority==='Assistant';if(!need)break;E.aiStep(g)}if(guard>=40)throw new Error('AI action guard stopped a possible loop.');setStatus('Opponent action complete.');render();pumpAI()}catch(e){setStatus('AI error: '+e.message,true);render()}},180)}
function newLocalMatch(providerReason=''){g=E.newGame(q('coreSeed').value||'FOCUSED-MAGIC-CORE',q('coreDifficulty').value);setStatus(providerReason?`Argentum failed (${providerReason}); Core Match switched visibly to local fallback.`:'New Core Match started in local fallback mode. You play first and skip the first-turn draw.');render();pumpAI()}
function newMatch(){if(window.FocusedMagicArgentum?.providerEnabled?.()){try{window.FocusedMagicArgentum.startFixture('core',{onProviderFail:(msg)=>newLocalMatch(msg)});setStatus('Core Match handed to Argentum; provider failure will fall back visibly.');}catch(e){newLocalMatch(e.message);}return;}newLocalMatch()}
q('coreBtn').addEventListener('click',()=>{q('coreModal').classList.add('open');if(!g)newMatch();else render()});q('coreClose').addEventListener('click',()=>q('coreModal').classList.remove('open'));q('coreNew').addEventListener('click',newMatch);q('coreDifficulty').addEventListener('change',()=>{if(g){g.difficulty=q('coreDifficulty').value;render()}});q('corePass').addEventListener('click',()=>act(()=>E.passPriority(g,'User'),'Priority passed.'));q('coreConcede').addEventListener('click',()=>act(()=>E.concede(g,'User'),'You conceded.'));
q('coreDeclareAttackers').addEventListener('click',()=>act(()=>{const ids=[...document.querySelectorAll('[data-core-attacker]:checked')].map(x=>x.dataset.coreAttacker);E.declareAttackers(g,'User',ids)},'Attackers declared.'));
q('coreDeclareBlocks').addEventListener('click',()=>act(()=>{const assigns={};for(const s of document.querySelectorAll('[data-core-block]'))if(s.value)assigns[s.dataset.coreBlock]=s.value;E.declareBlocks(g,'User',assigns)},'Blockers declared.'));
window.addEventListener('keydown',e=>{if(e.key==='Escape'&&q('coreModal').classList.contains('open'))q('coreModal').classList.remove('open')});
})();
